AeMS:
  # support tag, level: SMOKE > HIGH > MEDIUM > LOW > ALL
  run_case: "ALL"
  # version branch support: pico, femto, verizon
  version: femto
  northbound_ip_address: 172.0.16.42
  southbound_ip_address: 172.0.17.42
  mgmt_ip_address: 172.0.16.25
  backup_ip_address: 172.0.16.25

  # default user: admin to login
  web_user: admin
  web_pwd: casa
  northbound_user:
    username: ntapi
    password: casa1234
  backend_user: root
  backend_pwd: casa
  mysql:
    host:  172.0.16.25 # physical ip of mater or salve
    username: root
    password: casa
    db_name: hemsdb
  pico:
    profile_version: 4.5

HeNB:
  host: 172.0.13.20
  port: 22
  user_name: root
  password: casa # default pwd Ca$a@pex!234
  oam_file: /usr/sbin/oam
  TR069_file: /config/tr069/tr069_agent.ini


# mail setting:
# get help from mail server you use
# configure the smtp server and learn usage
mail:
  mail_host: smtp.qq.com
  host_port: 465
  mail_user: 78376474@qq.com
  mail_pwd: onctyyqycumtcbbb

# log setting
# level: CRITICAL> ERROR> WARN> INFO> DEBUG
log:
  file_name: test.log
  backup_count: 7
  console_level: DEBUG
  file_level: WARNING
  pattern: "%(asctime)s-%(funcName)s-%(levelname)s-%(message)s"
