AeMS:
  # version branch support: pico, femto, verizon
  version: pico
  northbound_ip_address: 172.0.16.99
  southbound_ip_address: 172.0.17.99
  mgmt_ip_address:
  backup_ip_address:
  # default user: admin to login
  web_user: admin
  web_pwd: casa
  backend_user: root
  backend_pwd: casa

HeNB:
  host: 172.0.13.100
  port: 22
  # default pwd Ca$a@pex!234
  user_name: root
  password: casa
  oam_file: /usr/sbin/oam
  TR069_file: /config/tr069/tr069_agent.ini

# HeNB Config
#file name
femtoconfig.ini:
  is_use_ipv6: 0
  ipsec: 0
parameter.csv:
  Long: 123456
  Lang: 987654

# mail setting:
# get help from mail server you use
# configure the smtp server and learn usage
mail:
  mail_host: smtp.qq.com
  host_port: 465
  mail_user: 78376474@qq.com
  mail_pwd: onctyyqycumtcbbb

# log setting
# level: CRITICAL> ERROR> WARN> INFO> DEBUG> NOTSET
log:
  file_name: test.log
  backup_count: 7
  console_level: DEBUG
  file_level: WARNING
  pattern: "%(asctime)s- %(funcName)s- %(levelname)s - %(message)s"
